<template>
  <div>
    <table>
      <thead>
        <tr>
          <th v-for="(header, index) in headers" :key="index">
            {{ header.text }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(item, index) in tbodydata" :key="index" v-html="item"></tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  data: () => {
    return {
      datos: [
        {
          id: 2,
          first_name: "Hamish",
          last_name: "McCambridge",
          email: "hmccambridge1@tuttocitta.it",
          gender: "Female",
          ip_address: "119.48.198.235",
        },
        {
          id: 1,
          first_name: "Nerita",
          last_name: "Tern",
          email: "ntern0@tripadvisor.com",
          gender: "Male",
          ip_address: "119.54.4.221",
        },
        {
          id: 3,
          first_name: "Mac",
          last_name: "Roullier",
          email: "mroullier2@harvard.edu",
          gender: "Female",
          ip_address: "38.51.95.114",
        },
        {
          id: 4,
          first_name: "Dinnie",
          last_name: "Pringle",
          email: "dpringle3@cafepress.com",
          gender: "Male",
          ip_address: "186.76.200.223",
        },
        {
          id: 5,
          first_name: "Shawnee",
          last_name: "Shelford",
          email: "sshelford4@usnews.com",
          gender: "Female",
          ip_address: "199.28.13.199",
        },
        {
          id: 6,
          first_name: "Rhonda",
          last_name: "Seczyk",
          email: "rseczyk5@mac.com",
          gender: "Female",
          ip_address: "53.173.121.1",
        },
        {
          id: 7,
          first_name: "Shana",
          last_name: "Allsobrook",
          email: "sallsobrook6@eepurl.com",
          gender: "Male",
          ip_address: "95.253.147.144",
        },
        {
          id: 8,
          first_name: "Dacie",
          last_name: "Hrinishin",
          email: "dhrinishin7@mysql.com",
          gender: "Female",
          ip_address: "231.206.243.97",
        },
        {
          id: 9,
          first_name: "Skipton",
          last_name: "Addington",
          email: "saddington8@tripadvisor.com",
          gender: "Male",
          ip_address: "88.17.11.17",
        },
        {
          id: 10,
          first_name: "Harriott",
          last_name: "Van Der Weedenburg",
          email: "hvanderweedenburg9@dion.ne.jp",
          gender: "Male",
          ip_address: "37.91.223.131",
        },
        {
          id: 11,
          first_name: "Lyndsay",
          last_name: "Stallan",
          email: "lstallana@soup.io",
          gender: "Male",
          ip_address: "154.79.166.0",
        },
        {
          id: 12,
          first_name: "Sauncho",
          last_name: "Girkin",
          email: "sgirkinb@slate.com",
          gender: "Male",
          ip_address: "163.124.162.229",
        },
        {
          id: 13,
          first_name: "Alva",
          last_name: "Beavon",
          email: "abeavonc@privacy.gov.au",
          gender: "Male",
          ip_address: "78.38.177.234",
        },
        {
          id: 14,
          first_name: "Drusy",
          last_name: "Woller",
          email: "dwollerd@cocolog-nifty.com",
          gender: "Female",
          ip_address: "170.91.82.61",
        },
        {
          id: 15,
          first_name: "Claudette",
          last_name: "Mant",
          email: "cmante@liveinternet.ru",
          gender: "Male",
          ip_address: "42.87.219.31",
        },
        {
          id: 16,
          first_name: "Corena",
          last_name: "Eykelbosch",
          email: "ceykelboschf@usgs.gov",
          gender: "Female",
          ip_address: "61.210.20.164",
        },
        {
          id: 17,
          first_name: "Sapphira",
          last_name: "Bogue",
          email: "sbogueg@washingtonpost.com",
          gender: "Female",
          ip_address: "197.84.233.16",
        },
        {
          id: 18,
          first_name: "Charley",
          last_name: "Pawson",
          email: "cpawsonh@sina.com.cn",
          gender: "Male",
          ip_address: "29.49.252.44",
        },
        {
          id: 19,
          first_name: "Yorgos",
          last_name: "Beceril",
          email: "ybecerili@wikipedia.org",
          gender: "Female",
          ip_address: "196.225.40.138",
        },
        {
          id: 20,
          first_name: "Myranda",
          last_name: "Shakle",
          email: "mshaklej@pcworld.com",
          gender: "Male",
          ip_address: "246.2.194.149",
        },
        {
          id: 21,
          first_name: "Dawn",
          last_name: "Tocque",
          email: "dtocquek@feedburner.com",
          gender: "Male",
          ip_address: "236.66.83.41",
        },
        {
          id: 22,
          first_name: "Malcolm",
          last_name: "Gofford",
          email: "mgoffordl@webs.com",
          gender: "Male",
          ip_address: "114.236.58.110",
        },
        {
          id: 23,
          first_name: "Adriana",
          last_name: "Gouda",
          email: "agoudam@upenn.edu",
          gender: "Female",
          ip_address: "163.225.38.50",
        },
        {
          id: 24,
          first_name: "Jule",
          last_name: "Zapatero",
          email: "jzapateron@timesonline.co.uk",
          gender: "Female",
          ip_address: "35.126.49.210",
        },
        {
          id: 25,
          first_name: "Wilhelmine",
          last_name: "Guerrier",
          email: "wguerriero@china.com.cn",
          gender: "Female",
          ip_address: "86.156.76.130",
        },
        {
          id: 26,
          first_name: "Salem",
          last_name: "Ashcroft",
          email: "sashcroftp@fda.gov",
          gender: "Male",
          ip_address: "223.187.245.92",
        },
        {
          id: 27,
          first_name: "Giffard",
          last_name: "Burlay",
          email: "gburlayq@list-manage.com",
          gender: "Male",
          ip_address: "247.114.223.26",
        },
        {
          id: 28,
          first_name: "Hobey",
          last_name: "Avramovic",
          email: "havramovicr@hugedomains.com",
          gender: "Male",
          ip_address: "176.154.136.153",
        },
        {
          id: 29,
          first_name: "Angus",
          last_name: "Ravel",
          email: "aravels@webmd.com",
          gender: "Male",
          ip_address: "138.43.41.187",
        },
        {
          id: 30,
          first_name: "L;urette",
          last_name: "Perford",
          email: "lperfordt@hao123.com",
          gender: "Male",
          ip_address: "250.53.202.77",
        },
        {
          id: 31,
          first_name: "Eduard",
          last_name: "O'Carran",
          email: "eocarranu@wikimedia.org",
          gender: "Male",
          ip_address: "98.26.140.14",
        },
        {
          id: 32,
          first_name: "Joshua",
          last_name: "Sambell",
          email: "jsambellv@gov.uk",
          gender: "Female",
          ip_address: "131.80.105.179",
        },
        {
          id: 33,
          first_name: "Merv",
          last_name: "Gjerde",
          email: "mgjerdew@netvibes.com",
          gender: "Female",
          ip_address: "105.42.252.1",
        },
        {
          id: 34,
          first_name: "Ealasaid",
          last_name: "Newbigging",
          email: "enewbiggingx@bloomberg.com",
          gender: "Male",
          ip_address: "116.92.23.219",
        },
        {
          id: 35,
          first_name: "Findley",
          last_name: "Bussel",
          email: "fbussely@tamu.edu",
          gender: "Male",
          ip_address: "198.235.89.156",
        },
        {
          id: 36,
          first_name: "Dorey",
          last_name: "Palfrie",
          email: "dpalfriez@amazon.co.jp",
          gender: "Female",
          ip_address: "118.47.119.152",
        },
        {
          id: 37,
          first_name: "Kathlin",
          last_name: "Haylock",
          email: "khaylock10@hatena.ne.jp",
          gender: "Agender",
          ip_address: "170.30.5.88",
        },
        {
          id: 38,
          first_name: "Billie",
          last_name: "Edsell",
          email: "bedsell11@amazon.de",
          gender: "Male",
          ip_address: "3.110.87.189",
        },
        {
          id: 39,
          first_name: "Gavan",
          last_name: "Sofe",
          email: "gsofe12@rambler.ru",
          gender: "Male",
          ip_address: "211.205.93.78",
        },
        {
          id: 40,
          first_name: "Jobey",
          last_name: "Dacca",
          email: "jdacca13@google.co.uk",
          gender: "Male",
          ip_address: "226.217.200.51",
        },
        {
          id: 41,
          first_name: "Brennan",
          last_name: "Ponder",
          email: "bponder14@vimeo.com",
          gender: "Female",
          ip_address: "34.29.188.13",
        },
        {
          id: 42,
          first_name: "Madel",
          last_name: "Luty",
          email: "mluty15@wikipedia.org",
          gender: "Female",
          ip_address: "108.248.225.241",
        },
        {
          id: 43,
          first_name: "Modestia",
          last_name: "Ruffy",
          email: "mruffy16@delicious.com",
          gender: "Female",
          ip_address: "14.49.130.247",
        },
        {
          id: 44,
          first_name: "Lisabeth",
          last_name: "Furbank",
          email: "lfurbank17@slate.com",
          gender: "Male",
          ip_address: "167.111.131.56",
        },
        {
          id: 45,
          first_name: "Jaquenetta",
          last_name: "Faulkener",
          email: "jfaulkener18@yelp.com",
          gender: "Female",
          ip_address: "105.159.109.155",
        },
        {
          id: 46,
          first_name: "Fara",
          last_name: "Burkinshaw",
          email: "fburkinshaw19@kickstarter.com",
          gender: "Female",
          ip_address: "221.208.12.28",
        },
        {
          id: 47,
          first_name: "Maurice",
          last_name: "Crangle",
          email: "mcrangle1a@toplist.cz",
          gender: "Female",
          ip_address: "218.122.232.71",
        },
        {
          id: 48,
          first_name: "Sondra",
          last_name: "Corkill",
          email: "scorkill1b@wunderground.com",
          gender: "Female",
          ip_address: "61.148.82.204",
        },
        {
          id: 49,
          first_name: "Roy",
          last_name: "Massingham",
          email: "rmassingham1c@naver.com",
          gender: "Male",
          ip_address: "175.229.163.98",
        },
        {
          id: 50,
          first_name: "Ernesto",
          last_name: "Grigolashvill",
          email: "egrigolashvill1d@jiathis.com",
          gender: "Female",
          ip_address: "214.168.74.244",
        },
        {
          id: 51,
          first_name: "Piotr",
          last_name: "O Sullivan",
          email: "posullivan1e@myspace.com",
          gender: "Genderqueer",
          ip_address: "243.17.128.118",
        },
        {
          id: 52,
          first_name: "Porty",
          last_name: "Wolfarth",
          email: "pwolfarth1f@disqus.com",
          gender: "Female",
          ip_address: "240.74.231.136",
        },
        {
          id: 53,
          first_name: "Marcelline",
          last_name: "Mountcastle",
          email: "mmountcastle1g@sun.com",
          gender: "Female",
          ip_address: "125.152.187.82",
        },
        {
          id: 54,
          first_name: "Cyril",
          last_name: "Heaker",
          email: "cheaker1h@ehow.com",
          gender: "Female",
          ip_address: "55.70.188.33",
        },
        {
          id: 55,
          first_name: "Hillie",
          last_name: "Chaulk",
          email: "hchaulk1i@amazon.co.uk",
          gender: "Male",
          ip_address: "120.61.19.68",
        },
        {
          id: 56,
          first_name: "Laurette",
          last_name: "Dewsbury",
          email: "ldewsbury1j@narod.ru",
          gender: "Female",
          ip_address: "153.239.184.176",
        },
        {
          id: 57,
          first_name: "Nicolais",
          last_name: "Lester",
          email: "nlester1k@gnu.org",
          gender: "Female",
          ip_address: "246.159.220.36",
        },
        {
          id: 58,
          first_name: "Howie",
          last_name: "Rignall",
          email: "hrignall1l@networksolutions.com",
          gender: "Female",
          ip_address: "125.204.149.165",
        },
        {
          id: 59,
          first_name: "Clea",
          last_name: "Eva",
          email: "ceva1m@tinyurl.com",
          gender: "Male",
          ip_address: "61.248.26.25",
        },
        {
          id: 60,
          first_name: "Aeriell",
          last_name: "Breston",
          email: "abreston1n@ucla.edu",
          gender: "Male",
          ip_address: "93.25.215.91",
        },
        {
          id: 61,
          first_name: "Innis",
          last_name: "Couper",
          email: "icouper1o@nationalgeographic.com",
          gender: "Genderfluid",
          ip_address: "245.65.126.165",
        },
        {
          id: 62,
          first_name: "Gilbertine",
          last_name: "Aronow",
          email: "garonow1p@ycombinator.com",
          gender: "Genderfluid",
          ip_address: "246.74.145.144",
        },
        {
          id: 63,
          first_name: "Vinni",
          last_name: "Lohmeyer",
          email: "vlohmeyer1q@blogtalkradio.com",
          gender: "Male",
          ip_address: "141.51.62.201",
        },
        {
          id: 64,
          first_name: "Carolynn",
          last_name: "Edlyne",
          email: "cedlyne1r@mozilla.org",
          gender: "Female",
          ip_address: "99.167.94.66",
        },
        {
          id: 65,
          first_name: "Britney",
          last_name: "Onslow",
          email: "bonslow1s@mail.ru",
          gender: "Male",
          ip_address: "101.38.37.243",
        },
        {
          id: 66,
          first_name: "Artair",
          last_name: "Goadbie",
          email: "agoadbie1t@samsung.com",
          gender: "Female",
          ip_address: "114.97.139.173",
        },
        {
          id: 67,
          first_name: "Wilden",
          last_name: "Giraudat",
          email: "wgiraudat1u@apple.com",
          gender: "Female",
          ip_address: "91.4.181.79",
        },
        {
          id: 68,
          first_name: "Will",
          last_name: "Laver",
          email: "wlaver1v@cmu.edu",
          gender: "Female",
          ip_address: "13.222.32.143",
        },
        {
          id: 69,
          first_name: "Linnie",
          last_name: "Wimes",
          email: "lwimes1w@bloglines.com",
          gender: "Male",
          ip_address: "241.53.141.118",
        },
        {
          id: 70,
          first_name: "Nelle",
          last_name: "Foulsham",
          email: "nfoulsham1x@epa.gov",
          gender: "Female",
          ip_address: "31.68.89.212",
        },
        {
          id: 71,
          first_name: "Asher",
          last_name: "Geelan",
          email: "ageelan1y@amazonaws.com",
          gender: "Bigender",
          ip_address: "160.161.50.86",
        },
        {
          id: 72,
          first_name: "Filberto",
          last_name: "Kennelly",
          email: "fkennelly1z@hhs.gov",
          gender: "Female",
          ip_address: "129.140.98.137",
        },
        {
          id: 73,
          first_name: "Ramsey",
          last_name: "Clewarth",
          email: "rclewarth20@stanford.edu",
          gender: "Male",
          ip_address: "105.2.116.225",
        },
        {
          id: 74,
          first_name: "Zeb",
          last_name: "Buttner",
          email: "zbuttner21@eventbrite.com",
          gender: "Male",
          ip_address: "154.12.143.146",
        },
        {
          id: 75,
          first_name: "Iggy",
          last_name: "Couth",
          email: "icouth22@telegraph.co.uk",
          gender: "Female",
          ip_address: "29.109.83.96",
        },
        {
          id: 76,
          first_name: "Peggy",
          last_name: "Cauldfield",
          email: "pcauldfield23@upenn.edu",
          gender: "Genderqueer",
          ip_address: "133.60.167.86",
        },
        {
          id: 77,
          first_name: "Natty",
          last_name: "Givens",
          email: "ngivens24@aboutads.info",
          gender: "Male",
          ip_address: "37.147.1.98",
        },
        {
          id: 78,
          first_name: "Wilburt",
          last_name: "Danielczyk",
          email: "wdanielczyk25@guardian.co.uk",
          gender: "Female",
          ip_address: "127.10.9.93",
        },
        {
          id: 79,
          first_name: "Abie",
          last_name: "Tacon",
          email: "atacon26@springer.com",
          gender: "Female",
          ip_address: "87.237.133.166",
        },
        {
          id: 80,
          first_name: "Cobbie",
          last_name: "McGuff",
          email: "cmcguff27@discovery.com",
          gender: "Female",
          ip_address: "66.87.16.119",
        },
        {
          id: 81,
          first_name: "Estevan",
          last_name: "Littefair",
          email: "elittefair28@ocn.ne.jp",
          gender: "Male",
          ip_address: "220.123.70.12",
        },
        {
          id: 82,
          first_name: "Petronella",
          last_name: "Gorse",
          email: "pgorse29@jalbum.net",
          gender: "Female",
          ip_address: "124.182.173.6",
        },
        {
          id: 83,
          first_name: "Garfield",
          last_name: "Joseff",
          email: "gjoseff2a@skyrock.com",
          gender: "Male",
          ip_address: "200.92.230.223",
        },
        {
          id: 84,
          first_name: "Holly-anne",
          last_name: "Craft",
          email: "hcraft2b@army.mil",
          gender: "Genderfluid",
          ip_address: "144.124.89.142",
        },
        {
          id: 85,
          first_name: "Jeana",
          last_name: "Hargerie",
          email: "jhargerie2c@bravesites.com",
          gender: "Male",
          ip_address: "226.249.74.38",
        },
        {
          id: 86,
          first_name: "Honey",
          last_name: "Liver",
          email: "hliver2d@guardian.co.uk",
          gender: "Female",
          ip_address: "174.189.120.159",
        },
        {
          id: 87,
          first_name: "Rik",
          last_name: "Velez",
          email: "rvelez2e@networkadvertising.org",
          gender: "Male",
          ip_address: "225.181.53.110",
        },
        {
          id: 88,
          first_name: "Kalil",
          last_name: "Gaishson",
          email: "kgaishson2f@tuttocitta.it",
          gender: "Female",
          ip_address: "22.24.50.142",
        },
        {
          id: 89,
          first_name: "Alfy",
          last_name: "de Courcy",
          email: "adecourcy2g@cargocollective.com",
          gender: "Male",
          ip_address: "176.253.54.96",
        },
        {
          id: 90,
          first_name: "Dorey",
          last_name: "Camerati",
          email: "dcamerati2h@163.com",
          gender: "Female",
          ip_address: "125.130.54.244",
        },
        {
          id: 91,
          first_name: "Nannette",
          last_name: "Moseley",
          email: "nmoseley2i@bing.com",
          gender: "Female",
          ip_address: "76.7.17.68",
        },
        {
          id: 92,
          first_name: "Jacklyn",
          last_name: "Rowthorne",
          email: "jrowthorne2j@stumbleupon.com",
          gender: "Female",
          ip_address: "209.237.155.227",
        },
        {
          id: 93,
          first_name: "Veradis",
          last_name: "Allender",
          email: "vallender2k@usa.gov",
          gender: "Male",
          ip_address: "226.178.10.219",
        },
        {
          id: 94,
          first_name: "Arnuad",
          last_name: "Filippozzi",
          email: "afilippozzi2l@tinyurl.com",
          gender: "Female",
          ip_address: "52.129.8.135",
        },
        {
          id: 95,
          first_name: "Orsa",
          last_name: "Guerreiro",
          email: "oguerreiro2m@telegraph.co.uk",
          gender: "Female",
          ip_address: "223.211.82.170",
        },
        {
          id: 96,
          first_name: "Florian",
          last_name: "Collen",
          email: "fcollen2n@comsenz.com",
          gender: "Female",
          ip_address: "54.210.200.172",
        },
        {
          id: 97,
          first_name: "Pavia",
          last_name: "Thal",
          email: "pthal2o@alexa.com",
          gender: "Male",
          ip_address: "49.109.5.92",
        },
        {
          id: 98,
          first_name: "Eb",
          last_name: "Balam",
          email: "ebalam2p@123-reg.co.uk",
          gender: "Female",
          ip_address: "222.70.231.69",
        },
        {
          id: 99,
          first_name: "Elizabet",
          last_name: "Geldert",
          email: "egeldert2q@example.com",
          gender: "Female",
          ip_address: "87.159.206.236",
        },
        {
          id: 100,
          first_name: "Jourdan",
          last_name: "Barnwell",
          email: "jbarnwell2r@cbslocal.com",
          gender: "Female",
          ip_address: "161.45.47.4",
        },
      ],
      headers: [
        { value: "id", text: "ID", type: "number" },
        { value: "gender", text: "genero" },
        { value: "first_name", text: "Nombre" },
        { value: "last_name", text: "Apellido" },
        { value: "ip_address", text: "ip", type: "number" },
      ],
      sortby: "ip_address",
    };
  },
  computed: {
    tbodydata: function () {
      console.log(this.fnSortByNumber(this.sortby));
      if (this.fnSortByNumber(this.sortby)) {
        this.datos.sort(this.fnOrdenInt);
      } else {
        this.datos.sort(this.fnOrderString);
      }
      const bodydata = this.datos.map((x) => {
        let item = "";
        this.headers.forEach((element) => {
          item += `<td>${x[element.value]}</td>`;
        });
        return item;
      });
      return bodydata;
    },
  },
  methods: {
    fnOrdenInt(a, b) {
      return parseInt(a[this.sortby], 10) - parseInt(b[this.sortby], 10);
    },
    fnOrderString(a, b) {
      if (a[this.sortby] > b[this.sortby]) {
        return 1;
      } else if (a[this.sortby] < b[this.sortby]) {
        return -1;
      }
      return 0;
    },
    fnSortByNumber(sortby) {
      let verification = false;
      this.headers.forEach((x) => {
        if (x.value == sortby) {
          verification = x.type ? (x.type == "number" ? true : false) : false;
        }
      });
      return verification;
    },
  },
};
</script>

<style>
</style>